export {
	MOTION_DURATION_MS,
	MOTION_ROUTE_DURATION_S,
	motionFadeExit,
	motionFadeHidden,
	motionFadeUpExit,
	motionFadeUpHidden,
	motionFadeUpVisible,
	motionFadeVisible,
	motionHeaderMenuItemExit,
	motionHeaderMenuItemHidden,
	motionHeaderMenuItemVisible,
	motionHeaderMenuStaggerDelay,
	motionMicroFadeHidden,
	motionMicroFadeUpExit,
	motionMicroFadeUpHidden,
	motionTransition,
	routeTransitionKey,
} from '@/kit/shared';
