import type { Metadata } from 'next';

import seoTable from '@/data/settings/seo.json';
import { BRAND, SITE_URL } from '@/lib/cms';

type SeoOverride = { title?: string; description?: string };

/** Hand-written titles/descriptions keyed by canonical path; they win over generated ones. */
const SEO_OVERRIDES = seoTable.SEO_OVERRIDES as Record<string, SeoOverride>;

export function seoOverride(canonical: string): SeoOverride | undefined {
	return SEO_OVERRIDES[canonical];
}

type OgImage = { url: string; width: number; height: number; alt: string };

const OG_SIZE = { width: 1200, height: 630 };

/** Default share card per template (generated by scripts/og.ts). */
const TEMPLATE_OG: [prefix: string, name: string][] = [
	['/tool/buyback-calculator', 'tool-buyback-calculator'],
	['/tool/eligibility-checker', 'tool-eligibility-checker'],
	['/tool/documentation-checklist', 'tool-documentation-checklist'],
	['/blog', 'blog'],
	['/locations', 'locations'],
	['/manufacturers', 'manufacturers'],
	['/faq', 'faq'],
	['/reviews', 'reviews'],
	['/case-studies', 'case-studies'],
	['/guidebook', 'guidebook'],
	['/info', 'guidebook'],
	['/learn', 'learn'],
	['/the-firm', 'firm'],
	['/team', 'firm'],
];

function templateOgImage(canonical: string, alt: string): OgImage {
	const match = TEMPLATE_OG.find(
		([prefix]) => canonical === prefix || canonical.startsWith(`${prefix}/`),
	);
	return { url: `/images/og/${match ? match[1] : 'default'}.jpg`, ...OG_SIZE, alt };
}

export function pageMetadata(input: {
	title: string;
	description: string;
	canonical: string;
	type?: 'website' | 'article';
	/** Featured image for the page (e.g. a blog post thumbnail). */
	image?: { url: string; width?: number; height?: number; alt?: string };
	publishedTime?: string;
	modifiedTime?: string;
	noindex?: boolean;
}): Metadata {
	const override = seoOverride(input.canonical);
	const title = override?.title ?? input.title;
	const description = override?.description ?? input.description;
	const url = `${SITE_URL}${input.canonical}`;
	const type = input.type ?? 'website';
	const image: OgImage = input.image
		? {
				url: input.image.url,
				width: input.image.width ?? OG_SIZE.width,
				height: input.image.height ?? OG_SIZE.height,
				alt: input.image.alt ?? title,
			}
		: templateOgImage(input.canonical, title);
	return {
		title: { absolute: title },
		description,
		alternates: { canonical: input.canonical },
		...(input.noindex ? { robots: { index: false, follow: true } } : {}),
		openGraph: {
			title,
			description,
			url,
			type,
			siteName: BRAND.name,
			locale: 'en_US',
			images: [image],
			...(type === 'article'
				? {
						publishedTime: input.publishedTime,
						modifiedTime: input.modifiedTime,
						authors: [`${SITE_URL}/team/brian-cline`],
					}
				: {}),
		},
		twitter: {
			card: 'summary_large_image',
			title,
			description,
			images: [image.url],
		},
	};
}
