import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { editorialRecordFromMdc } from '../src/lib/cms/content/mdc';

const repoRoot = resolve(import.meta.dirname, '..');
const collectionsRoot = join(repoRoot, 'content/collections');

type CollectionSpec = {
	dir: 'blog' | 'info' | 'locations';
	jsonKey: 'BLOG_POSTS' | 'EDITORIAL_PAGES' | 'LOCATION_PAGES';
	outFile: string;
};

const COLLECTIONS: CollectionSpec[] = [
	{ dir: 'blog', jsonKey: 'BLOG_POSTS', outFile: 'content/data/items/blog.json' },
	{
		dir: 'info',
		jsonKey: 'EDITORIAL_PAGES',
		outFile: 'content/data/items/editorial.json',
	},
	{
		dir: 'locations',
		jsonKey: 'LOCATION_PAGES',
		outFile: 'content/data/items/locations.json',
	},
];

function indexEntryFromMdc(raw: string) {
	const record = editorialRecordFromMdc(raw);
	return {
		slug: record.slug,
		title: record.title,
		description: record.description,
		date: record.date,
		modified: record.modified,
		sourceUrl: record.sourceUrl,
		kind: record.kind,
		categories: record.categories,
		seoTitle: record.seoTitle,
		seoDescription: record.seoDescription,
		...(record.thumbnail ? { thumbnail: record.thumbnail } : {}),
		...(record.thumbnailAlt ? { thumbnailAlt: record.thumbnailAlt } : {}),
	};
}

const mdcRawByKey: Record<string, string> = {};

for (const spec of COLLECTIONS) {
	const dir = join(collectionsRoot, spec.dir);
	const files = readdirSync(dir)
		.filter((name) => name.endsWith('.mdc'))
		.sort();
	const items = files.map((name) => {
		const raw = readFileSync(join(dir, name), 'utf8');
		const entry = indexEntryFromMdc(raw);
		const kindKey = entry.kind === 'info' ? 'info' : entry.kind === 'blog' ? 'blog' : 'location';
		mdcRawByKey[`${kindKey}:${entry.slug}`] = raw;
		return entry;
	});
	const outPath = join(repoRoot, spec.outFile);
	writeFileSync(outPath, `${JSON.stringify({ [spec.jsonKey]: items }, null, 2)}\n`);
	console.log(`Wrote ${items.length} index rows → ${spec.outFile}`);
}

const bundlePath = join(repoRoot, 'src/lib/cms/content/mdc-bundle.ts');
writeFileSync(
	bundlePath,
	`/** Generated by scripts/syncmdc.ts — do not edit. */\nexport const mdcRawByKey: Record<string, string> = ${JSON.stringify(mdcRawByKey)};\n`,
);
console.log(
	`Wrote ${Object.keys(mdcRawByKey).length} MDC bodies → src/lib/cms/content/mdc-bundle.ts`,
);
