import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { editorialRecordFromMdc, splitMdc } from '../src/lib/cms/content/mdc';
import manufacturersTable from '../content/data/items/manufacturers.json';
import topicsTable from '../content/data/settings/topics.json';

const repoRoot = resolve(import.meta.dirname, '..');
const collectionsRoot = join(repoRoot, 'content/collections');

type CollectionSpec = {
	dir: 'blog' | 'info' | 'locations';
	jsonKey: 'BLOG_POSTS' | 'EDITORIAL_PAGES' | 'LOCATION_PAGES';
	outFile: string;
};

const COLLECTIONS: CollectionSpec[] = [
	{ dir: 'blog', jsonKey: 'BLOG_POSTS', outFile: 'content/data/items/blog.json' },
	{
		dir: 'info',
		jsonKey: 'EDITORIAL_PAGES',
		outFile: 'content/data/items/editorial.json',
	},
	{
		dir: 'locations',
		jsonKey: 'LOCATION_PAGES',
		outFile: 'content/data/items/locations.json',
	},
];

function escapeRegExp(value: string) {
	return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const FALLBACK_TOPIC = topicsTable.BLOG_TOPICS.find((topic) => 'fallback' in topic)!.slug;

const SUBJECT_TOPICS = topicsTable.BLOG_TOPICS.filter((topic) => !('fallback' in topic)).map(
	(topic) => ({
		slug: topic.slug,
		pattern: new RegExp(`\\b(?:${topic.pattern})\\b`, 'gi'),
	}),
);

const BRAND_ALIASES = topicsTable.BRAND_ALIASES as Record<string, string[]>;
const BRAND_TOPICS = manufacturersTable.MANUFACTURERS.map((brand) => {
	const aliases = BRAND_ALIASES[brand.slug] ?? [brand.name.toLowerCase()];
	return {
		slug: brand.slug,
		pattern: new RegExp(`\\b(?:${aliases.map(escapeRegExp).join('|')})\\b`, 'gi'),
	};
});

function countMatches(pattern: RegExp, text: string) {
	return text.match(pattern)?.length ?? 0;
}

/**
 * Tags a blog post with subject topics and manufacturer brands for topic hubs, related posts
 * and manufacturer → article links. Headline matches count heavily; body mentions need to be
 * repeated so a passing reference doesn't tag the post.
 */
function classifyPost(raw: string) {
	const { frontmatter, body } = splitMdc(raw);
	const headline = `${frontmatter.title} ${frontmatter.slug.replace(/-/g, ' ')}`;
	const text = body.replace(/\]\([^)]*\)/g, ']');
	const score = (pattern: RegExp) =>
		countMatches(pattern, headline) * 5 + countMatches(pattern, text);
	const pick = (candidates: { slug: string; pattern: RegExp }[], min: number, max: number) =>
		candidates
			.map((candidate) => ({ slug: candidate.slug, score: score(candidate.pattern) }))
			.filter((candidate) => candidate.score >= min)
			.sort((a, b) => b.score - a.score)
			.slice(0, max)
			.map((candidate) => candidate.slug);
	const topics = pick(SUBJECT_TOPICS, 6, 3);
	return {
		topics: topics.length > 0 ? topics : [FALLBACK_TOPIC],
		brands: pick(BRAND_TOPICS, 3, 2),
	};
}

function indexEntryFromMdc(raw: string) {
	const record = editorialRecordFromMdc(raw);
	return {
		slug: record.slug,
		title: record.title,
		description: record.description,
		date: record.date,
		modified: record.modified,
		sourceUrl: record.sourceUrl,
		kind: record.kind,
		categories: record.categories,
		seoTitle: record.seoTitle,
		seoDescription: record.seoDescription,
		...(record.thumbnail ? { thumbnail: record.thumbnail } : {}),
		...(record.thumbnailAlt ? { thumbnailAlt: record.thumbnailAlt } : {}),
		...(record.kind === 'blog' ? classifyPost(raw) : {}),
	};
}

const mdcRawByKey: Record<string, string> = {};

for (const spec of COLLECTIONS) {
	const dir = join(collectionsRoot, spec.dir);
	const files = readdirSync(dir)
		.filter((name) => name.endsWith('.mdc'))
		.sort();
	const items = files.map((name) => {
		const raw = readFileSync(join(dir, name), 'utf8');
		const entry = indexEntryFromMdc(raw);
		const kindKey = entry.kind === 'info' ? 'info' : entry.kind === 'blog' ? 'blog' : 'location';
		mdcRawByKey[`${kindKey}:${entry.slug}`] = raw;
		return entry;
	});
	const outPath = join(repoRoot, spec.outFile);
	writeFileSync(outPath, `${JSON.stringify({ [spec.jsonKey]: items }, null, 2)}\n`);
	console.log(`Wrote ${items.length} index rows → ${spec.outFile}`);
}

const bundlePath = join(repoRoot, 'src/lib/cms/content/mdc-bundle.ts');
writeFileSync(
	bundlePath,
	`/** Generated by scripts/syncmdc.ts — do not edit. */\nexport const mdcRawByKey: Record<string, string> = ${JSON.stringify(mdcRawByKey)};\n`,
);
console.log(
	`Wrote ${Object.keys(mdcRawByKey).length} MDC bodies → src/lib/cms/content/mdc-bundle.ts`,
);
